--- 
 - name: error handling
   become: true
   hosts: localhost
   tasks: 
       - name: this task will fail
         ansible.builtin.command: ls -lrt
         register: result
         ignore_errors: true

       - name: print the output
         ansible.builtin.debug: 
            var: result

       - name:  print the registered value
         ansible.builtin.debug:
           msg: "play confinued despite of the failure"
         
       - name: print the result got failed
         ansible.builtin.debug:
           msg: "detected a failure"
         when: result.failed

       - name: print the result got succeded
         ansible.builtin.debug:
            msg: "succeded"
         when: not result.failed